"""FastAPI exception handlers for normalized API error responses."""

import logging

from fastapi import Request, FastAPI
from fastapi.exceptions import RequestValidationError
from fastapi.encoders import jsonable_encoder
from fastapi.responses import JSONResponse

from src.exceptions.custom_exceptions import AppBaseException
from src.schemas.response.common_response import ErrorResponse

logger = logging.getLogger(__name__)


def add_exception_handlers(app: FastAPI):
    """Register application-wide exception handlers.

    Args:
        app: FastAPI application that should receive the handlers.

    Returns:
        None: Handlers are registered on the provided application instance.
    """
    
    @app.exception_handler(AppBaseException)
    async def app_exception_handler(request: Request, exc: AppBaseException):
        """Convert domain exceptions into standardized error responses.

        Args:
            request: Incoming HTTP request that raised the exception.
            exc: Application exception containing response metadata.

        Returns:
            JSONResponse: Error payload with the exception status code.
        """
        logger.warning(f"AppException: {exc.error_code} - {exc.message}")
        response = ErrorResponse(
            error_code=exc.error_code,
            message=exc.message
        )
        return JSONResponse(status_code=exc.status_code, content=response.model_dump())

    @app.exception_handler(RequestValidationError)
    async def validation_exception_handler(request: Request, exc: RequestValidationError):
        """Handle FastAPI request validation failures.

        Args:
            request: Incoming HTTP request with invalid parameters or body.
            exc: Validation exception generated by FastAPI/Pydantic.

        Returns:
            JSONResponse: Validation error payload with HTTP 422 status.
        """
        logger.error(f"Validation Error: {exc.errors()}")
        response = ErrorResponse(
            error_code="VALIDATION_ERROR",
            message="Invalid request parameters",
            details=jsonable_encoder(exc.errors())
        )
        return JSONResponse(status_code=422, content=response.model_dump())

    @app.exception_handler(Exception)
    async def global_exception_handler(request: Request, exc: Exception):
        """Handle unexpected exceptions without exposing internals.

        Args:
            request: Incoming HTTP request that triggered the failure.
            exc: Unhandled exception raised by application code.

        Returns:
            JSONResponse: Generic internal server error payload.
        """
        logger.critical(f"Unhandled Exception: {str(exc)}", exc_info=True)
        # Avoid leaking stack traces or infrastructure details to API clients.
        response = ErrorResponse(
            error_code="INTERNAL_SERVER_ERROR",
            message="An unexpected error occurred."
        )
        return JSONResponse(status_code=500, content=response.model_dump())
