spring.application.name=vehicle-rental-system

# Server Port
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_rental_system_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
# 'update' automatically generates tables based on our Entities
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=admin
spring.security.user.password=admin

# --- JWT SECURITY CONFIGURATION ---
# Senior Note: This is a 256-bit Base64 encoded string.
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiration time in milliseconds (86400000 ms = 24 hours)
jwt.expiration=86400000