export const ROUTES = {
    ROOT: '/',
    LOGIN: '/login',
    RESET_PASSWORD: '/reset-password',
    DASHBOARD: '/dashboard',
    USERS: '/users',
    USER_CREATE: '/users/create',
    USER_EDIT: '/users/edit/:id',
    CANDIDATES: '/candidates',
    CANDIDATE_CREATE: '/candidates/create',
    CANDIDATE_DETAILS: '/candidates/:id',
    CANDIDATE_EDIT: '/candidates/edit/:id',
    CANDIDATE_RESUME: '/candidates/:id/resume',
    CANDIDATE_STATUS_HISTORY: '/candidates/:id/status-history',
    JOBS: '/jobs',
    JOB_CREATE: '/jobs/create',
    JOB_DETAILS: '/jobs/:id',
    JOB_EDIT: '/jobs/edit/:id',
    INTERVIEWS: '/interviews',
    INTERVIEW_SCHEDULE: '/interviews/schedule',
    INTERVIEW_EDIT: '/interviews/edit/:id',
    INTERVIEW_ASSIGNED: '/interviews/assigned',
    INTERVIEW_DETAILS: '/interviews/:id',
    INTERVIEW_FEEDBACK: '/interviews/:id/feedback',
};

